name: Extract Clips

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'clips/**'
  workflow_dispatch:

jobs:
  process-clips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Extract clips
        run: |
          mkdir -p out
          for i in ./clips/*.clips; do
            echo "Processing $i"
            python3 clips_extractor.py "$i" ./out
          done

      - name: Package output
        run: |
          zip -r clips.zip ./out/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clips-zip
          path: clips.zip
          if-no-files-found: error
